List<String> quotes = [
  "The way to get started is to quit talking and begin doing. - Walt Disney",
  "Life is what happens when you're busy making other plans. - John Lennon",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "The only way to do great work is to love what you do. - Steve Jobs",
  "Don't cry because it's over, smile because it happened. - Dr. Seuss",
  "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "In the end, it's not the years in your life that count. It's the life in your years. - Abraham Lincoln",
  "Strive not to be a success, but rather to be of value. - Albert Einstein",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "You miss 100% of the shots you don't take. - Wayne Gretzky",
  "Life is what happens when you're busy making other plans. - John Lennon",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "The only way to do great work is to love what you do. - Steve Jobs",
  "Don't cry because it's over, smile because it happened. - Dr. Seuss",
  "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "In the end, it's not the years in your life that count. It's the life in your years. - Abraham Lincoln",
  "Strive not to be a success, but rather to be of value. - Albert Einstein",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "You miss 100% of the shots you don't take. - Wayne Gretzky",
  "The best time to plant a tree was 20 years ago. The second best time is now. - Chinese Proverb",
  "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
  "The journey of a thousand miles begins with one step. - Lao Tzu",
  "Change your thoughts and you change your world. - Norman Vincent Peale",
  "I have not failed. I've just found 10,000 ways that won't work. - Thomas A. Edison",
  "It always seems impossible until it is done. - Nelson Mandela",
  "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
  "The only way to do great work is to love what you do. - Steve Jobs",
  "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
  "If you can dream it, you can achieve it. - Zig Ziglar",
  "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
  "Quality is not an act, it is a habit. - Aristotle",
  "The best revenge is massive success. - Frank Sinatra",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
  "Do not go where the path may lead, go instead where there is no path and leave a trail. - Ralph Waldo Emerson",
  "What you get by achieving your goals is not as important as what you become by achieving your goals. - Zig Ziglar",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "It's not whether you get knocked down, it's whether you get up. - Vince Lombardi",
  "The way to get started is to quit talking and begin doing. - Walt Disney",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "The only way to do great work is to love what you do. - Steve Jobs",
  "Don't cry because it's over, smile because it happened. - Dr. Seuss",
  "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "In the end, it's not the years in your life that count. It's the life in your years. - Abraham Lincoln",
  "Strive not to be a success, but rather to be of value. - Albert Einstein",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "You miss 100% of the shots you don't take. - Wayne Gretzky",
  "The best time to plant a tree was 20 years ago. The second best time is now. - Chinese Proverb",
  "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
  "The journey of a thousand miles begins with one step. - Lao Tzu",
  "Change your thoughts and you change your world. - Norman Vincent Peale",
  "I have not failed. I've just found 10,000 ways that won't work. - Thomas A. Edison",
  "It always seems impossible until it is done. - Nelson Mandela",
  "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
  "The only way to do great work is to love what you do. - Steve Jobs",
  "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
  "If you can dream it, you can achieve it. - Zig Ziglar",
  "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
  "Quality is not an act, it is a habit. - Aristotle",
  "The best revenge is massive success. - Frank Sinatra",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
  "Do not go where the path may lead, go instead where there is no path and leave a trail. - Ralph Waldo Emerson",
  "What you get by achieving your goals is not as important as what you become by achieving your goals. - Zig Ziglar",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "It's not whether you get knocked down, it's whether you get up. - Vince Lombardi",
  "The way to get started is to quit talking and begin doing. - Walt Disney",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "The only way to do great work is to love what you do. - Steve Jobs",
  "Don't cry because it's over, smile because it happened. - Dr. Seuss",
  "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "In the end, it's not the years in your life that count. It's the life in your years. - Abraham Lincoln",
  "Strive not to be a success, but rather to be of value. - Albert Einstein",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "You miss 100% of the shots you don't take. - Wayne Gretzky",
  "The best time to plant a tree was 20 years ago. The second best time is now. - Chinese Proverb",
  "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
  "The journey of a thousand miles begins with one step. - Lao Tzu",
  "Change your thoughts and you change your world. - Norman Vincent Peale",
  "I have not failed. I've just found 10,000 ways that won't work. - Thomas A. Edison",
  "It always seems impossible until it is done. - Nelson Mandela",
  "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
  "The only way to do great work is to love what you do. - Steve Jobs",
  "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
  "If you can dream it, you can achieve it. - Zig Ziglar",
  "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
  "Quality is not an act, it is a habit. - Aristotle",
  "The best revenge is massive success. - Frank Sinatra",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
  "Do not go where the path may lead, go instead where there is no path and leave a trail. - Ralph Waldo Emerson",
  "What you get by achieving your goals is not as important as what you become by achieving your goals. - Zig Ziglar",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "It's not whether you get knocked down, it's whether you get up. - Vince Lombardi"
];
